export const generalOptions = {
    country: [
      { value: "Saudi Arabia", label: "Saudi Arabia" },
      { value: "Kuwait", label: "Kuwait" },
      { value: "Egypt", label: "Egypt" },
      { value: "United Arabia Emarites", label: "United Arabia Emarites" },
      { value: "India", label: "India" },
      { value: "Pakistan", label: "Pakistan" },
      { value: "Bangladesh", label: "Bangladesh" },
      { value: "Malaysia", label: "Malaysia" },
      { value: "Canada", label: "Canada" },
      { value: "Tanzania", label: "Tanzania" },
      { value: "Bahrin", label: "Bahrin" },
      { value: "Jordan", label: "Jordan" },
      { value: "Qatar", label: "Qatar" },
      { value: "Oman", label: "Oman" },
      { value: "United States Of America", label: "United States Of America" },
      { value: "Germany", label: "Germany" },
    ],
    experience: [
      { value: "Less than 1 years", label: "Less than 1 years" },
      { value: "1-3 years", label: "1-3 years" },
      { value: "3-5 years", label: "3-5 years" },
      { value: "More than 5 years", label: "More than 5 years" },
    ],
   "role": [
    { "value": "QA", "label": "QA" },
    { "value": "Executive", "label": "Executive" },
    { "value": "QA Manager", "label": "QA Manager" },
    { "value": "Academic", "label": "Academic" },
    { "value": "Senior Executive", "label": "Senior Executive" },
    { "value": "Research Scientist", "label": "Research Scientist" },
    { "value": "Electrical and Validation Manager", "label": "Electrical and Validation Manager" },
    { "value": "Laboratory Technician or Specialist", "label": "Laboratory Technician or Specialist" },
    { "value": "Sales or Marketing Specialist", "label": "Sales or Marketing Specialist" },
    { "value": "Owner", "label": "Owner" },
    { "value": "Laboratory Manager", "label": "Laboratory Manager" },
    { "value": "Technical and Service Support Specialist", "label": "Technical and Service Support Specialist" },
    { "value": "Strategic Planning Head", "label": "Strategic Planning Head" },
    { "value": "CQO", "label": "CQO" },
    { "value": "IT Specialist", "label": "IT Specialist" },
    { "value": "Manager", "label": "Manager" },
    { "value": "SQA", "label": "SQA" },
    { "value": "Senior Chemical Analyst", "label": "Senior Chemical Analyst" },
    { "value": "Administrative Support", "label": "Administrative Support" },
    { "value": "HR", "label": "HR" },
    { "value": "Quality Assurance", "label": "Quality Assurance" }
  ],
    aiFamiliarity: [
      { value: "Not at all Familiar", label: "Not at all Familiar" },
      { value: "Somewhat Familiar", label: "Somewhat Familiar" },
      { value: "Familiar", label: "Familiar" },
      { value: "Very Familiar", label: "Very Familiar" },
    ],
    aiUsage: [
      { value: "Not Used", label: "Not Used" },
      { value: "Limited use", label: "Limited use" },
      { value: "Moderate use", label: "Moderate use" },
      { value: "Extensive use", label: "Extensive use" },
    ],
  };

  // Options for Challenges Section
export  const challengeOptions = [
  { value: "Not a Barrier", label: "Not a Barrier" },
  { value: "Minor Barrier", label: "Minor Barrier" },
    { value: "Moderate Barrier", label: "Moderate Barrier" },
    { value: "Significant Barrier", label: "Significant Barrier" },
    { value: "Major Barrier", label: "Major Barrier" },
  ];